import type { Patient, Session } from "./types"

/** Demo data for Rehup only — Diversa is loaded from the Google Sheet. */
export const patients: Patient[] = [
  {
    id: "PT-20001",
    name: "Jane Smith",
    lastVisit: "2026-08-24",
    clinic: "rehup",
    initials: "JS",
  },
  {
    id: "PT-20002",
    name: "Emily Taylor",
    lastVisit: "2026-07-30",
    clinic: "rehup",
    initials: "ET",
  },
  {
    id: "PT-20003",
    name: "Oliver Wright",
    lastVisit: "2026-08-05",
    clinic: "rehup",
    initials: "OW",
  },
  {
    id: "PT-20004",
    name: "Mia Cohen",
    lastVisit: null,
    clinic: "rehup",
    initials: "MC",
  },
  {
    id: "PT-20005",
    name: "Noah Levi",
    lastVisit: "2026-08-18",
    clinic: "rehup",
    initials: "NL",
  },
]

export const sessions: Session[] = [
  {
    id: "SES-2001",
    patientId: "PT-20001",
    patientName: "Jane Smith",
    initials: "JS",
    date: "2026-08-24",
    description: "Vaccination booster administered.",
    cost: 85,
    currency: "GBP",
    out: false,
    reportsRosangela: true,
    clinic: "rehup",
  },
  {
    id: "SES-2002",
    patientId: "PT-20002",
    patientName: "Emily Taylor",
    initials: "ET",
    date: "2026-08-25",
    description: "Annual physical exam.",
    cost: 120,
    currency: "GBP",
    out: false,
    reportsRosangela: false,
    clinic: "rehup",
  },
  {
    id: "SES-2003",
    patientId: "PT-20003",
    patientName: "Oliver Wright",
    initials: "OW",
    date: "2026-08-26",
    description: "Chest pain evaluation, home visit.",
    cost: 220,
    currency: "GBP",
    out: true,
    reportsRosangela: true,
    clinic: "rehup",
  },
  {
    id: "SES-2004",
    patientId: "PT-20005",
    patientName: "Noah Levi",
    initials: "NL",
    date: "2026-09-01",
    description: "Sports physical.",
    cost: 85,
    currency: "GBP",
    out: false,
    reportsRosangela: false,
    clinic: "rehup",
  },
]
